= Vendredi 15:30 / 16:15 - Migrer ses APIs vers GraphQL: pourquoi? comment!
Thomas SCHWENDER <https://github.com/ardemius[@ardemius]>
// Handling GitHub admonition blocks icons
ifndef::env-github[:icons: font]
ifdef::env-github[]
:status:
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]
:imagesdir: ../images
:source-highlighter: highlightjs
// Next 2 ones are to handle line breaks in some particular elements (list, footnotes, etc.)
:lb: pass:[<br> +]
:sb: pass:[<br>]
// check https://github.com/Ardemius/personal-wiki/wiki/AsciiDoctor-tips for tips on table of content in GitHub
:toc: macro
//:toclevels: 3
// To turn off figure caption labels and numbers
:figure-caption!:

toc::[]

Par *Guillaume Scheibel*. +
icon:tags[] Key words : GraphQL, Kotlin, APIs

====
Guillaume est développeur chez Expedia à Londres et a travaillé durant quelques années en France pour une grosse société de services. Il a également co-créé le JUG pour la région de Strasbourg (ElsassJUG) et contribue à 2 projets open-sources (Hibernate OGM et Infinispan). De temps en temps, il parle à différentes conférences (Soft-Shake, Devoxx FR, MA et BE, CodeMotion ES) ou JUGs.
====

== Overview

====
Comme beaucoup, Expedia déploie des APIs que ce soit pour ses applications mobiles, les plateformes de conversations (Alexa etc) ou simplement pour alimenter les pages web. Avec plusieurs dizaines APIs différentes s'appuyant sur le modèle REST, l'ensemble s'est retrouvé inconsistant en terme de type: comment représenter un prix ou une date, en terme style: utilisation des variables en paramètres ou dans le chemin etc.

L'un des effets de cette inconsistance est d'avoir les équipes utilisants ces APIs de passer trop de temps à maintenir ces différents styles et donc autant de temps qui n'est pas employé au service du développement de fonctionnalités pour les utilisateurs finaux.

Avec une hétérogénéité des clients, toutes les données retournées ne sont pas forcément nécessaires. Pourquoi obligatoirement retourner l'image associée à un hôtel pour la plateforme Alexa?

Durant cette présentation nous verrons comment Expedia utilise GraphQL (schéma et langage) pour améliorer ces APIs tant au niveau technique que fonctionnel.
====

== Notes

REX de ce qui s'est passé chez *Expedia* (qui était chez Microsoft il y a 25 ans)

*BFF* (Backend For Frontend) : Pour simplifier le front, on va leur demander d'intégrer *1 seule API*


















