= Jeudi 09:20 - Keynote - La médecine de demain
Thomas SCHWENDER <icon:github[] https://github.com/Ardemius/[GitHub] / icon:twitter[role="aqua"] https://twitter.com/thomasschwender[@thomasschwender]>
// Handling GitHub admonition blocks icons
ifndef::env-github[:icons: font]
ifdef::env-github[]
:status:
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]
:imagesdir: ./images
:source-highlighter: highlightjs
:highlightjs-languages: asciidoc
// We must enable experimental attribute to display Keyboard, button, and menu macros
:experimental:
// Next 2 ones are to handle line breaks in some particular elements (list, footnotes, etc.)
:lb: pass:[<br> +]
:sb: pass:[<br>]
// check https://github.com/Ardemius/personal-wiki/wiki/AsciiDoctor-tips for tips on table of content in GitHub
:toc: macro
:toclevels: 4
// To number the sections of the table of contents
//:sectnums:
// Add an anchor with hyperlink before the section title
:sectanchors:
// To turn off figure caption labels and numbers
:figure-caption!:
// Same for examples
//:example-caption!:
// To turn off ALL captions
// :caption:

toc::[]

== Notes

Par Jean-Michel Billaut

* "La grande disruption", voir https://billaut.typepad.com/jm/la-grande-disruption/[son blog]
* Il reparle d'Emmanuelle Charpentier et des *ciseaux génétiques du CRISPR/CAS9*.
	** (Je vous conseille d'écouter le podcast https://www.podcastscience.fm/dossiers/2015/06/28/crispr-la-mutagenese-qui-croustille/["Podcast Science" sur le sujet])

//-

* On peut se faire *séquencer son génome* par différentes startup actuellement (peut être illégal en France,  à vérifier).
* La Chine se lance à fond dans cette *nouvelle e-Santé*.
* Obama l'a dit dernièrement : on va bientôt *se faire soigner spécifiquement*, *en fonction de son séquençage*.

En France, on a perdu des milliards dans des systèmes nationaux mal conçus :

	* cloud français
	* payé des militaires
	* carnet de santé numérique 

D'ici peu (?) On aura des *séquenceurs portables* sur nous, ainsi que notre *dossier médical numérique*, et le séquenceur pourra nous dire si ce que nous mangeons est bon pour NOUS (spécifique à la personne, peux-tu manger ce pain sachant que tu es proche du diabète de type 2 ?)

* Les anglais sont en train de séquencer les cancéreux dans un même data center, alors qu'il y en a 80 différents et autorisés en France (grosse connerie car pas possible de faire tourner du big data sur tous ces serveurs)
	** Notre corps est finalement mathématique, un ensemble de data.

De nombreuses startups, surtout américaines, se lancent dans la e-Santé :

	* analyse en temps réel à partir d'une goutte de sang
	* création d'un nouveau foie à partir de vos cellules souches

Votez sur lui sur le site de la primaire.org.












