= Vendredi 09:25 - Keynote - De l'utopie de la fin du travail au digital labour
Thomas SCHWENDER <icon:github[] https://github.com/Ardemius/[GitHub] / icon:twitter[role="aqua"] https://twitter.com/thomasschwender[@thomasschwender]>
// Handling GitHub admonition blocks icons
ifndef::env-github[:icons: font]
ifdef::env-github[]
:status:
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]
:imagesdir: ./images
:source-highlighter: highlightjs
:highlightjs-languages: asciidoc
// We must enable experimental attribute to display Keyboard, button, and menu macros
:experimental:
// Next 2 ones are to handle line breaks in some particular elements (list, footnotes, etc.)
:lb: pass:[<br> +]
:sb: pass:[<br>]
// check https://github.com/Ardemius/personal-wiki/wiki/AsciiDoctor-tips for tips on table of content in GitHub
:toc: macro
:toclevels: 4
// To number the sections of the table of contents
//:sectnums:
// Add an anchor with hyperlink before the section title
:sectanchors:
// To turn off figure caption labels and numbers
:figure-caption!:
// Same for examples
//:example-caption!:
// To turn off ALL captions
// :caption:

toc::[]

== Notes

Par Sébastien Broca

IMPORTANT: Peur commune : *Vague d'automatisation* = *fin du travail* / chômage pour les classes moyennes 

* Est-ce fondé ? L'histoire nous montre que pas tellement (machine à tisser de jacquard, automatisation automobile)
    ** Ont déclenché la colère des ouvriers, mais n'ont finalement pas supprimé le travail. 

//-

* Exemple de l'*Utopie* de *Thomas More* (l'île d'Utopie et les Utopiens) 
    ** Toutes ces oeuvres d'anticipation (19e siècle) mettent en avant la *fin du travail répétitif et rébarbatif*, *au profit des loisirs et de la liberté, à l'aide des machines*.

Est-ce applicable aujourd'hui ? 

    * *"le travail n'est plus accompli par devoir moral et intérêt financier"* surtout valable pour les hackers / développeurs, *"Il est accompli par intérêt et passion"*

Cela correspond-il a la réalité ? 

    * situations très différentes : employés de Google (super conditions de travail, bon salaire) / taxis précaires d'Uber

Création d'un *grand nombre de petits boulots précaires dans l'ère du numérique* (coursier, etc.)

Conclusion :

    * Nous n'assistons pas à une disparition du travail, mais à une *transformation* de ce dernier.
    * L'Utopie doit être une boussole devant nous indiquer la direction à suivre
    * Il nous faut de *la loi en plus du code* :
    
        ** garantir la solidarité sociale
        ** sécuriser les parcours professionnels discontinus 
        ** protéger les non codeurs dans ce nouveau monde 


