= Retour d'XP projet BNP Connexis Cash "Cloudifie ton monolithe"
Thomas SCHWENDER <https://sgithub.fr.world.socgen/tschwend041717[@thomas.schwender]>
// Handling GitHub admonition blocks icons
ifndef::env-github[:icons: font]
ifdef::env-github[]
:status:
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]
:imagesdir: ./images
:source-highlighter: highlightjs
// Next 2 ones are to handle line breaks in some elements (list, footnotes, etc.)
:lb: pass:[<br> +]
:sb: pass:[<br>]
// check https://github.com/Ardemius/personal-wiki/wiki/AsciiDoctor-tips for tips on table of content in GitHub
:toc: macro
:toclevels: 3
 
toc::[]
 
Présenté à la SGCIB, dans le cadre des BBLs, par François Berthault (Taland)
 
== Abstract
 
Use cases : OVH trop petit, plutôt la paye de tout IKEA... (gros projet)
 
On va tacler les différents niveaux de complexité comme dans un jeu vidéo : avec des "monstres" combattre. +
On les bat et on récupère des bonus...
 
== Complexité
 
Environnement :
 
* Plusieurs pays (France, Allemagne, Asie, Inde, etc.)
* waterfall
* vieilles technos : Hibernate, IBM Websphere, Oracle, XDoclet, application écrite en Flex (Flash)
 
-> crash en 2010 : développeurs absents, turn-over, ça ne pouvait plus durer -> cela a donné un levier pour transformer l'environnement (à commencer par supprimer Flash...)
 
== Artisanat
 
Début de la transformation, passage à l'Intégration Continue en 2012.
 
Donc 2012, on a un monolithe, MAIS sous IC. +
1h30 pour corriger une faute de frappe.
 
== Monolithe
 
La genèse de leurs microservices : la création d'un simple Business Components en mode message.
 
== Peur du changement
 
L'équipe voulait absolument quitter WAS !
 
D'où passage en microservice :
 
* single focus high cohesion
* petit
* en DEHORS de WAS
* autonome
* son propre code
* sa propre BDD
* sa propre implem
* son propre cycle de livraison
* protocole de comm lâche
 
2 équipes partent en POC pour les microservices : ils peuvent choisir leur techno (2016) :
 
* dropwizard
* Spring Boot
 
Problème : 3 technos de dev différentes, 3 modes de déploiement différents, 3 raisons de faire râler les OPS... +
-> 90% des équipes faisaient du Spring, donc choix de Spring Boot
 
Industrialisation : choix de *Maven Archetype*
 
== Chaos technique
 
Beaucoup de microservices arrivent.
 
API Gateway via la stack Netflix OSS.
 
Histoire : voir la présentation de Josh LONG (anciennement Spring Source) "Beautiful microservices"
 
Après cela, suffit d'exposer les microservices via `/feature-a/**` et `/feature-b/**`
 
== Ambiguité
 
Pour "quoi migrer" : passage au Domain Driven Design
 
Découverte des frontières (Bounded context)
 
== Densité
 
migration en "faux" microservices POUR COMMENCER :
 
* dans le monolithe, on commence par isoler le code du microservice, et on expose les dépendances
* puis on ISOLE les tables, et on les migre
                ** -> *TRES COMPLIQUE* : nécessite du temps et beaucoup de tests
 
== Silots organisationnelles
 
* 2 directions
* séparation entre les OPS et les Devs
 
-> création de feature team !
 
* accompagnement par des coachs Agile (les BA avaient l'habitude d'écrire des specs de 400 pages devant durer 6 mois, les OPS n'avaient pas l'habitude de livraisons très fréquentes)
 
La création de cette équipe a pu se faire en "off-shore" : pas à l'étranger, mais indépendament des autres équipes (passage des OPS de l'équipe aux OPS centraux "ceinture noire" de BNP) +
Les OPS centraux mettent Docker et Rancher (orchestrateur, comme un Kubernetes) à disposition.
 
En mode Lab : donc *root sur les machines*
 
Processflow :
 
Java -> Jar -> spring boot qui rend le jar executable -> Docker -> push sur DTR (*artifactory*)
 
Là passage à Docker compose et Rancher : provisionnement automatique instantanée contre 3 ans de boulot avec les WAS...
 
== Cohérence des données
 
Choix du CQRS / Event Sourcing plutôt que :
 
* fusion des microservices
* produit Oracle : Change Data Capture (mais considéré comme anti DevOps)
* vues matérialisées : non, car les microservices doivent avoir leurs propres données
 
Dès lors (CQRS avec ségrégation entre lecture et écriture), plus de requêtes synchrones : on passe au vrai microservices.
 
== Synthèse
 
* Il faut avoir une CI avant de commencer quoi que ce soit
* ne pas perdre le plaisir de coder : donc ne pas avoir peur de se tromper
* standardiser les microservices
* l'API Gateway (qui respecte le Top 10 OWASP)
* DDD pour identifier les frontières de vos microservices
* *tester une feature dans une équipe cross-fonctionnelle pour avoir des Ojectifs partagés avec les OPS*
* bénéficier d'une infra as code avec Docker et du provisionnement auto avec Rancher
* CQRS / Event sourcing