= StarTECH - 2020/11/03
Thomas SCHWENDER <https://github.com/ardemius[@ardemius]>
// Handling GitHub admonition blocks icons
ifndef::env-github[:icons: font]
ifdef::env-github[]
:status:
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]
:imagesdir: images
:source-highlighter: highlightjs
// Next 2 ones are to handle line breaks in some particular elements (list, footnotes, etc.)
:lb: pass:[<br> +]
:sb: pass:[<br>]
// check https://github.com/Ardemius/personal-wiki/wiki/AsciiDoctor-tips for tips on table of content in GitHub
:toc: macro
:toclevels: 1
// To turn off figure caption labels and numbers
//:figure-caption!:
// Same for examples
//:example-caption!:
// To turn off ALL captions
:caption:

toc::[]

Présentation technique de la solution de Data Analytics Indexima durant la réunion mensuelle StarTECH de novembre

== Abstract

Indexima est une boîte que je suis depuis plusieurs années, et qui propose une solution très performante en sortie de data lake, pour accélérer certains types de traitements. +
Pour donner quelques billes, la solution joue le rôle d'un datamart in memory, un peu comme un cube OLAP derrière le lake (les données chargées dans Indexima vont faire l'objet de pré-traitements).

== Notes
















