= DevFest Paris - 2020/02/14
Thomas SCHWENDER <https://github.com/ardemius[@ardemius]>
// Handling GitHub admonition blocks icons
ifndef::env-github[:icons: font]
ifdef::env-github[]
:status:
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]
:imagesdir: images
:source-highlighter: highlightjs
// Next 2 ones are to handle line breaks in some particular elements (list, footnotes, etc.)
:lb: pass:[<br> +]
:sb: pass:[<br>]
// check https://github.com/Ardemius/personal-wiki/wiki/AsciiDoctor-tips for tips on table of content in GitHub
:toc: macro
:toclevels: 1
// To turn off figure caption labels and numbers
//:figure-caption!:
// Same for examples
//:example-caption!:
// To turn off ALL captions
:caption:

toc::[]

Présenté au Palais des Congrés d'Issy, https://goo.gl/maps/xYdir7CWMTnyeHt46[25 Avenue Victor Cresson, 92130 Issy-les-Moulineaux]
Site : https://devfest.gdgparis.com/

== 11h50 - RGPD avec apache BEAM et BigQuery

Par Mehdi BEN HAJ ABBES

.abstract
----
Je vous propose une live démo d’implémentation du droit à l’oubli avec l’anonymisation/dé anonymisation sélective de vos données personnelles en batch et en streaming, le tout en moins de 15 min :)
----

== 12h15 - Kubernetes enfin ultra simple et léger avec K3S

Par Sébastien Moreno (Ippon Bordeaux)

.abstract
----
L’installation d’un cluster Kubernetes a longtemps été une tâche lourde pour l’Ops ou le Dev. Mais on arrive maintenant dans une ère de maturité dans les distributions Kubernetes, avec notamment Rancher, Openshift… mais aussi les installeurs du cloud comme EKS de AWS. Ici je propose d’explorer dans un Quickie une autre distribution issue de Rancher, ultra-légère, ultra simple, prête pour la prod et l’IOT. K3S débarrasse Kubernetes de sa complexité de ses plugins superflus et change Kubernetes en simple binaire à lancer sur vos machines. Au programme: explication de ce que ça cache sous le capot et de la démo !
----

== 15h00 - Dockerfile - Les bonnes pratiques

Par Guillaume LOURS et Jérémie DROUET (Docker tous les deux)

.abstract
----
A partir d’un Dockerfile pris “au hasard” sur Github, comme un bon vieux monolithe, nous allons, en appliquant les bonnes pratiques, transformer cette application en un ensemble de microservices réutilisables et compréhensibles

On commencera par externaliser les services utilisés par notre application en utilisant des images existantes et les associant dans un fichier Compose.

Nous allons optimiser notre premier jet en vidant les caches et en supprimant les layers inutiles générés lors du build de notre application.

On découpera les différentes étapes de build pour ne pas avoir à conserver les dépendances de développement dans l’image finale

Nous améliorerons la maintenabilité en utilisant des images officielles plutôt qu’en installant à la main nos dépendances.

Nous allons voir comment éviter de faire tourner notre application en tant que root.
----

== 16h00 - Spinnaker - Continuous Delivery on Kubernetes

Par Julien Calderan (Xebia), Mohamed Chaaben (D2SI), René Okouya (WeScale)

.abstract
----
Le déploiement continue est la nouvelle façon de mettre en production les applications à moindre risque. Cependant la mise en place des stratégies de déploiement peut s’avérer souvent complexe.

Spinnaker est un outil open source de déploiement continu multi-region, multi-cloud, développé par Netflix en collaboration avec d’autre grands acteurs du Cloud tel que Google, Microsoft, Amazon et Pivotal.

Durant cet atelier nous mettrons en place un environnement de déploiement sur Kubernetes, automatisé et fiabilisé grâce à Spinnaker. Venez découvrir comment déployer sereinement vos applications grâce à Spinnaker !
----

