= Paris JUG - 2020/05/12 - JHipster, Azure, GitHub, Codespaces
Thomas SCHWENDER <https://github.com/ardemius[@ardemius]>
// Handling GitHub admonition blocks icons
ifndef::env-github[:icons: font]
ifdef::env-github[]
:status:
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]
:imagesdir: images
:source-highlighter: highlightjs
// Next 2 ones are to handle line breaks in some particular elements (list, footnotes, etc.)
:lb: pass:[<br> +]
:sb: pass:[<br>]
// check https://github.com/Ardemius/personal-wiki/wiki/AsciiDoctor-tips for tips on table of content in GitHub
:toc: macro
:toclevels: 1
// To turn off figure caption labels and numbers
//:figure-caption!:
// Same for examples
//:example-caption!:
// To turn off ALL captions
:caption:

toc::[]

MeetUp virtuel du fait du confinement. +
https://www.parisjug.org/xwiki/wiki/oldversion/view/Meeting/20200512

== Abstract

Dans les locaux virtuels de Microsoft Teams https://aka.ms/parisjuglive

----
18h45 à 19h00 : Accueil

19h00 à 20h00: Développer en Java dans le cloud

En cette période de pandémie, nous allons voir comment mieux développer en Java "dans le cloud". Pas que pour le déploiement en production, mais également pour développer au jour le jour.
Nous parlerons évidemment de JHipster et d'Azure, mais ce sera l'occasion de faire une première démo de Codespaces, l'IDE intégré à GitHub qui vient tout juste d'être annoncé (cela devrait être une première en France, voire mondiale...).
Ainsi, vous pourrez être productifs à la maison, ou sur votre ordinateur personnel, comme si vous étiez à votre bureau - les transports et l'open space en moins!

par Julien Dubois

Après... : 3ème mi-temps virtuelle des juggers sur Microsoft Teams ;-)
----

== Notes

* Présentation du dernier JHipster par Julien DUBOIS.

* Ils utilisent https://github.com/jhipster/prettier-java[Prettier for Java] avec un pre-commit hook pour GitHub

* Rappel : Microsoft a racheté Citus Data (2019/01)

* *GitHub Codespaces est la version en ligne de Visual Studio Code*
	** github.com/jdubois/jdubois-codespaces : Codespaces Dockerfile for developing with modern Java
	** Pour le coût de ce Visual Studio Online, voir le lien "pricing" dans ce repo


