= Soirée Docker & Java 9 - 2017/06/13
Thomas SCHWENDER <https://github.com/ardemius[@ardemius]>
:icons: font
:imagesdir: images
:source-highlighter: highlightjs
// Next 2 ones are to handle line breaks in some particular elements (list, footnotes, etc.)
:lb: pass:[<br> +]
:sb: pass:[<br>]
// check https://github.com/Ardemius/personal-wiki/wiki/AsciiDoctor-tips for tips on table of content in GitHub
:toc: macro

toc::[]

== Overview

https://www.parisjug.org/xwiki/wiki/oldversion/view/Meeting/20170613[Descriptif de la soirée sur le site du ParisJUG.]

== 19h30 - Java and docker, what’s up?

Par Jean-Christophe Sirot et Charles Sabourdin

Pourquoi quand vous demandez a mettre en production java dans docker, on vous fait la grimace ? +
Pourquoi vos "container" crashent si souvent et pourquoi les nodes swapent-ils tant ? +
Partageons ensemble nos découvertes et réflexions sur java dans docker.

=== Live demo

Création d'un programme Java ayant pour but de partir en OutOfMemoryError Java Heap Space, lançé dans n containers Docker.

Utilisation des options Java :

* `-XX:+UnlockExperimentalVMOptions`
* `-XX:+UseCGroupMemoryLimitForHeap`

Conclusion : 

* Déléguer la gestion de la mémoire à l'image Docker (et ne pas le faire soi-même via `XMS` ou `XMX`) +
* `-XshowSettings:vm` : très intéressant pour la récupération d'infos
* `-XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/dump` : pour la récupération facile du Heap dump
* `-XX:NativeMemoryTracking=summary` +
Ou `jcmd <pid> VM.native_memory summary`

Un bon cas pratique illustrant la configuration de la mémoire pour des containers Docker.

=== Ressources

* slides dispo sur GitHub https://github.com/kanedafromparis/java-docker-slides

== 21h - Java 9 modulo les modules

Par Jean-Michel Doudoux

Le sujet principal de Java 9 est le support de la modularité mais Java 9 propose aussi de nombreuses autres fonctionnalités. Ce talk a pour but de faire une revue des principales d’entre-elles en attendant la sortie de Java 9 : support de standards, nouvelles API, évolutions dans certaines API, mises à jour des outils du JDK et améliorations de la JVM.

Présentation des nouveautés de Java 9 qui ne sont *PAS* le projet Jigsaw.

=== Ressources

https://fr.slideshare.net/jmdoudoux/java-9-modulo-les-modules-devoxx-fr-2017


