= Vendredi 09:00 / 10:30 - Keynotes
Thomas SCHWENDER <https://github.com/ardemius[@ardemius]>
// Handling GitHub admonition blocks icons
ifndef::env-github[:icons: font]
ifdef::env-github[]
:status:
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]
:imagesdir: ../images
:source-highlighter: highlightjs
// Next 2 ones are to handle line breaks in some particular elements (list, footnotes, etc.)
:lb: pass:[<br> +]
:sb: pass:[<br>]
// check https://github.com/Ardemius/personal-wiki/wiki/AsciiDoctor-tips for tips on table of content in GitHub
:toc: macro
//:toclevels: 3
// To turn off figure caption labels and numbers
:figure-caption!:

toc::[]

// ifdef::env-github[]
// https://www.youtube.com/watch?v=XXXXXX[vidéo de la présentation sur YouTube]
// endif::[]
// ifdef::env-browser[]
// video::XXXXXX[youtube, width=640, height=480]
// endif::[]

image::0

== Software Heritage: pourquoi et comment preserver le patrimoine logiciel de l'Humanite

Voir https://cfp.devoxx.fr/2018/talk/NRE-7647/Software_Heritage%3A_pourquoi_et_comment_preserver_le_patrimoine_logiciel_de_l'Humanite

Par Roberto Di Cosmo

=== Overview

====
Le logiciel est au cœur de notre société numérique au point et le code source des logiciels contient une part croissante de nos connaissances scientifiques, techniques et organisationnelles, au point d'etre devenu desormais une partie integrante du patrimoine de l'Humanité.

La mission de *Software Heritage* est de veiller à ce que cette précieuse masse des connaissances soit collectée, préservée, organisée et mise à la disposition de tous.

Nous faisons cela pour de multiples raisons. +
Pour préserver les connaissances scientifiques et technologiques intégrées dans le code source du logiciel, qui est une partie précieuse de notre patrimoine. Pour permettre un meilleur développement et réutilisation des logiciels pour la société et l'industrie, en construisant la plus grande base de connaissances de logiciels. Et pour favoriser une science meilleure, en fournissant la plus grande base de code pour la recherche sur les logiciels et en créant l'infrastructure pour préserver et partager les logiciels de recherche, complément nécéssaire de l'Open Access, et brique essentielle pour la reproducibilité.
====

=== Notes

Roberto nous rappelle nos jeunes années (et les siennes) au travers de Doom et Quake :wink:

Il insiste au travers de divers exemples, sur l'importance de sauvegarder, conserver le code source, car ce dernier renferme une grande partie de notre savoir actuelle.
Il rappelle l'envoi d'un homme sur la lune, avec ses 60 000 lignes de code à une époque ou rien n'existait.

Présentation de *Software Heritage*

image::1

* *Mission* : Collect, preserve and share the source code of ALL the software that is available

image::2

Comment ça marche ? +
L'objectif est de sauvegarde le code de *toutes* les plateformes disponibles (GitHub, GitLab, etc.) +
Les plateformes étant différentes (avec des protocoles différents), cela nécessite la création d'un certain nombre d'adapteurs.

* Représente un peu moins de 200 To
* l'architecture de la solution est assimilable à un (très) grand arbre de Merkel

Roberto nous propose un accès développeur à leur site :

image::5

* http://archive.softwareheritage.org/browse (credential: devoxx / 2018)

Il faut une prise de conscience que le code que nous écrivons fait partie du patrimoine de l'humanité.

Software Heritage recrute, mais à surtout besoin d'aide, et de contributeurs. +
Et s'il y a des sociétés qui veulent devenir sponsor, elles sont les bienvenues.

image::6

== French-Road

https://cfp.devoxx.fr/2018/talk/ESJ-4326/French-Road

Par Emmanuel PESENTI, Président de French-road, est architecte des systèmes d'information actuellement en poste dans un des services du premier ministre.

=== Overview

====
La France, et l’Europe qui est dans le même état, que nous qualifions de « pré-numérique« , se trouvent à portée de l’Asie et des Etats Unis. 

Si nous n’accélérons pas notre transformation digitale, nous serons le terrain de bataille du numérique américain, et du numérique chinois. +
Mais en France, comment passer à l'ère digitale (sans manquer d'R) ? Par la confiance et la maturité digitale, les véritables inducteurs d'une nation digitale, sur un continent dont l'histoire est forgée de périodes terribles et de valeurs fortes. 

Nous exigeons pour notre pays et pour l’Europe, l'excellence juridique, citoyenne, sécuritaire, économique, organisationnelle et politique. rien que ça ! +
Mais ça se mérite un peu quand même ! +
Notre initiative se propose donc d’amorcer la mise en œuvre de la x-road française, et nous l’appelons la French-Road.
====

=== Notes

Constat d'Emmanuel : nous (la France) sommes en retard comparé aux GAFAM et à leurs équivalents chinois. +
Un retard chiffrable de 5 à 30 ans.

French-road veut installer la X-road en France et en Europe.

*French-road* veut mettre en place une autre carte d'ID numérique (ressemble au modèle estonien), permettant un ensemble de services numériques autour d'elle.

Cette carte sera associée à une version disponible sur mobile.

image::7

Dans la mise en place de ce dispositif, la sécurité et la "cyber-hygiène" sont essentielles. +
La blockchain fait de nouveau partie des technos sous-jacentes, semble être devenu la solution de base pour ces besoins.

Emmanuel explique qu'avec son équipe, ils se sont clairement inspirés du modèle estonien.

.Bénéfices de l'identité digitale
image::8

Emmanuel explique que l'Estonie est le pays le moins corrompu du monde.

* système de vote estonien : ouvert pendant 1 semaine, seulement le dernier vote compte
* leur grande peur depuis leur indépendance il y a 27 ans : être envahis par la Russie
	** si cela arrive, le gouvernement part en diaspora à leur e-ambassade du Luxembourg, et peut gouverner depuis un téléphone portable

Gestion des données par le X-road : l'objectif est de *rationaliser la data*.

image::9

Nous sommes à l'aube d'une transformation (révolution) de notre administration et de notre mode de vie (enfin !)

.X-road platform architecture
image::10

* X-road est complètement décentralisée et déconcentrée

.architecture technique
image::11

Le système estonien est RGPD natif.

French-road recrute !

== L'ordinateur quantique

Voir https://cfp.devoxx.fr/2018/talk/MLP-9385/L'ordinateur_quantique

Par David Rousset, “Program Manager” pour Microsoft Corp au sein de la division PAX de Windows.

=== Overview

====
L'informatique quantique est entrain d'arriver et va opérer un changement majeur.

Nous tenterons d’expliquer pourquoi nous devons avoir ce changement de paradigme gigantesque avec la mort imminente de la loi de Moore. +
Qu’est-ce qu’un ordinateur quantique ? Que peut-il faire de différent d’un ordinateur classique ? Comment programmer un algorithme quantique ? 

Voilà quelques questions que nous allons essayer de résoudre ensemble.
====

=== Notes

Actuellement 1 transistor = 14 nanomètres, quand 1 cellule humaine fait 7 micromètres.

Mais, rappel, au bout d'un moment, en-dessous d'une certaine taille, les propriétés de la physique change ! +
On ne pourra réduite sans cesse la taille des transistors, d'ici peu, l'architecture des processeurs va donc changer (si elle veut continuer à progresser).

Richard Feynman, père fondateur de la mécanique quantique.

Mécanique quantique : tant que l'état n'est pas mesuré, ce dernier n'est finalement pas défini. +
En fait, quand on demande la mesure, on *force l'état*.

Donc, exemple pour simplifier, avec 4 qBits, leurs 16 valeurs vont pouvoir toutes être stockées *en même temps*. +
-> C'est ce qui va permettre de booster les performances de l'informatique quantique.

.Pièce de monnaie quantique
image::12

Algorithmes quantiques actuels :

* based on probabilities

Actuellement, dans le domaine de la chimie des molécules, on dépasse déjà les possibilités des ordinateurs classiques.

IMPORTANT: Actuellement la NSA a arrêté tout investissement technologique autre que l'informatique quantique.

Pour tester l'informatique quantique :

image::14

IBM, Google, Microsoft cherchent à développer, améliorer leur ordinateur quantique

David explique que s'il s'est à la base intéressé à cette technologie, c'est dans l'espoir que cela puisse aider son fils, touché d'une maladie génétique. +

Il nous donne les ressources suivantes sur l'informatique quantique :

image::15

=== Avis

Super talk à revoir ! +
Et dire que cela devait être mon sujet pour ce Devoxx ! (que je n'ai, hélas !, pas eu le temps de terminer)

== L'Homme sur Mars : Pourquoi ? Comment ? Les défis.

Voir https://cfp.devoxx.fr/2018/talk/OLV-7275/L'Homme_sur_Mars_:_Pourquoi_%3F_Comment_%3F_Les_defis.

Par Richard Heidmann, Ancien élève de l’École Polytechnique et de l’École Nationale Supérieure de l’Aéronautique et de l’Espace, Richard Heidmann est ingénieur en propulsion spatiale.

=== Overview

====
Bien que reconnus, les enjeux du projet d'un débarquement sur la Planète rouge : connaissances scientifiques, innovation, influence géostratégique, motivation de la jeunesse, n’ont pas conduit à une décision de programme, les décideurs politiques considérant l’échéance trop lointaine, les coûts et les risques trop importants. +
Mais l'initiative privée acquiert une influence grandissante. La société SpaceX a dévoilé en 2016 son projet de transporteur interplanétaire à coût réduit, fondé sur le principe de réutilisabilité totale. Une révolution astronautique.

Nous possédons les technologies à appliquer pour nous établir sur Mars. +
Cependant l’édification d’une colonie exigera un modèle économique crédible, permettant la mobilisation d’investissements à long terme.

Va-t-on assister à une aventure martienne conduite par un entrepreneur visionnaire ? +
Ou la force d'entraînement de celui-ci conduira-t-elle les agences spatiales à collaborer avec le privé ? +
Quoi qu'il advienne, le paysage est bouleversé et on devrait assister à une dynamisation du projet Homme sur Mars.
====

=== Notes

Mars est une destination privilégiée, car elle dispose d'un large spectre de ressources :

image::16

Quelles sont les motivations politiques ?

image::17

* avancement des connaissances : mystères de la vie, comprendre la Terre
* développement économique
* c'est un moyen de *remotiver la jeunesse dans les métiers de la technique*

Au niveau gouvernementale, les agences ne semblent pas avoir l'envie d'aller sur Mars (elles n'en donnent vraiment pas l'impression, )

* pas assez de budget
* projets irréalistes (on pourrait presque dire volontairement, cf Richard, histoire d'être sûr que cela ne se fasse pas...)

Actuellement, si une solution doit venir, elle viendra du domaine privé, avec la société *SpaceX d'Elon Musk*.

On commence à imaginer la colonisation

image::18

Si on doit faire quelque chose sur Mars, cela doit être *spécifique à Mars*. +
Sinon, autant, de loin, le faire ailleurs...

En conclusion

image::19


