= Devoxx France 2022 - Buzz words and synthesis
Thomas SCHWENDER <icon:github[] https://github.com/Ardemius/[GitHub] / icon:twitter[role="aqua"] https://twitter.com/thomasschwender[@thomasschwender]>
// Handling GitHub admonition blocks icons
ifndef::env-github[:icons: font]
ifdef::env-github[]
:status:
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]
:imagesdir: ./images
:source-highlighter: highlightjs
:highlightjs-languages: asciidoc
// We must enable experimental attribute to display Keyboard, button, and menu macros
:experimental:
// Next 2 ones are to handle line breaks in some particular elements (list, footnotes, etc.)
:lb: pass:[<br> +]
:sb: pass:[<br>]
// check https://github.com/Ardemius/personal-wiki/wiki/AsciiDoctor-tips for tips on table of content in GitHub
:toc: macro
:toclevels: 4
// To number the sections of the table of contents
//:sectnums:
// Add an anchor with hyperlink before the section title
:sectanchors:
// To turn off figure caption labels and numbers
:figure-caption!:
// Same for examples
//:example-caption!:
// To turn off ALL captions
// :caption:

toc::[]

.2022/xx/yy - Vidéos disponibles sur YouTube
IMPORTANT: Les vidéos des conférences seront bientôt disponibles sur sur https://www.youtube.com/channel/UCsVPQfo5RZErDL41LoWvk0A[chaîne YouTube de Devoxx France].

* Les photos du salon sont visibles ici : https://www.devoxx.fr/2022/05/02/devoxx-france-2022-les-photos/

== Buzz words & Technos qui ont le vent en poupe

* *Kubernetes* partout pour tout ce qui est Cloud Native
	** avec *Prometheus* et *Grafana* pour le monitoring et le dashboarding 
* *Quarkus* est de plus en plus adopté, et passe de plus en plus en PROD (Décathlon, etc.) 
* *Kafka* encore et toujours partout
* *Java Flight Recorder* pour le monitoring de la JVM (Hotspot)
* on parle toujours de *microservices* (même si moins que les années passées), MAIS toujours en mentionnant le DDD (*Domain Driven Design*)

== Technos dont on parle moins (ou plus !)

== Conf à voir sur YouTube

* Architecture hexagonale
* Votre cerveau est nul !

== Sociétés et personnes rencontrées

* *Astrachain*
	** société spécialisée dans la sécurité, a créé une solution permettant de chiffrer vos données "sans clé".
		*** Bon, dans les faits, il y a bien entendu une clé, mais cette dernière est gérée de façon complètement transparente côte Astrachain
		*** et vos données sont en fait splittées, avec la clé, dans *différents* Cloud providers
		*** Par contre, ce que je leur ai demandé, c'est dans quelle mesure cela ne faisait pas que "décaler le problème" ? +
		Car, si la clé est gérée de leur côté, même si split, dès lors qu'un assaillant arrive à se faire passer pour vous et à se connecter à leur solution, il va pouvoir accéder à vos données... +
			**** Et ils m'ont confirmé que c'était un aspect de leur solution sur lequel ils travaillaient actuellement pour le rendre plus secure.
	** https://www.astrachain.com/fr/accueil/
* *COSIUM* : 100 milliards de capitalisation boursière, a dernièrement racheté Essilor
	** présent dans de multiples domaines, mais surtout le milieu de l'optique médicale
* *Michelin*
	** 150 000 employés et 3000 ITs. Couvre tous les métiers de l'IT. +
	J'ai discuté avec un DevOps qui leur a mis en place une CI/CD complète avec déploiement sur Kubernetes
* *Harness* : CI/CD avec modules de Feature Flags, SRE, Security Test (OWASP)
	** par contre boîte jeune avec modèle de licensing surprenant : par service pour le "core" CI/CD, puis par user pour les modules annexes (Feature Flags et autres) +
	Donc quand on prend des modules en plus, on se retrouve vite à avoir une facturation "custom" directement discutée avec Harness
* *Promyze* : une plateforme de partage de bonnes pratiques de codage
	** https://promyze.com/fr/
	** J'ai échangé avec Cédric TEYTON (cedric.teyton@promyse.com), l'un des créateurs de l'outil
	** Promyze permet de partager des bonnes pratiques au sein d'une équipe de développement
	** Promyze permet échanger de mettre à jour une base de connaissance des bonnes pratiques
		*** Base de connaissances publique mise à disposition par Promyze
	** Promyze est hébergé sur Clever Cloud
	** Jetez un oeil à leurs *bonnes pratiques de dev* : https://bestcodingpractices.dev

* J'ai croisé *Medhi* maintenant chez Ippon, et nous avons parlé du programme Black Belt et de la stratégie que j'ai proposée chez Softeam
	** Black Belt : par ceinture, 12 SLOs à atteindre
	** ils ont développé une application Black Belt spécifique pour permettre aux Ippons de suivre leur avancement dans les parcours

* *Miretis* : 
	** 900 personnes
	** tous les leaders de communautés sont au 4/5 pour gérer l'activité de leur communauté

== Avis sur le salon

Au final, *pas de grosse annonce technologique* durant ce salon. +
Les technos phares restent les mêmes (Kubernetes, Kafka, poussée de Quarkus), mais la proximité avec Devoxx France 2021 (début octobre dernier) et l'impact du COVID ont du freiner les développements chez bien des éditeurs.

La chose très positive que je constate, c'est le *développement du craft* dont l'on entend maintenant parler partout. +
*L'accent sur la qualité*, sur la méthodologie (DDD de plus en plus fréquent, surtout avec les microservices qui se rapprochent toujours un peu plus d'une phase de maturité) se sentait dans beaucoup de talks.


