= Devoxx France 2019 - Buzz words and synthesis
Thomas SCHWENDER <https://github.com/ardemius[@ardemius]>
// Handling GitHub admonition blocks icons
ifndef::env-github[:icons: font]
ifdef::env-github[]
:status:
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]
:imagesdir: ../images
:source-highlighter: highlightjs
// Next 2 ones are to handle line breaks in some particular elements (list, footnotes, etc.)
:lb: pass:[<br> +]
:sb: pass:[<br>]
// check https://github.com/Ardemius/personal-wiki/wiki/AsciiDoctor-tips for tips on table of content in GitHub
:toc: macro
//:toclevels: 3
// To turn off figure caption labels and numbers
:figure-caption!:

toc::[]

// .2019/xx/xx - Vidéos disponibles sur YouTube
// IMPORTANT: Les vidéos des conférences sont maintenant disponibles sur YouTube, via la playlist https://www.youtube.com/playlist?list=xxx[Devoxx France 2019] de la chaîne Devoxx Fr

== Buzz words & Technos qui ont le vent en poupe

* *Kubernetes / Istio*
* *Quarkus* : comme évolution de Thorntail en tant qu'implémentation de Eclipse MicroProfile, mais est également beaucoup plus que cela, et monte en puissance !
* *GraalVM*
* *Microservices*
	** Et surtout microservices avec Kubernetes, et *Istio, comme service mesh*, pour gérer les fonctionnalités transverses du Capability Model
	** Plusieurs conf sur *MicroProfile*, comme quoi Java Enterprise continue d'évoluer ! 🙂
* *GraphQL*
* *gRPC* (forcément aidé par Kubernetes)

== Technos dont on parle moins, ou plus

* Excepté le talk sur le "shit coin", *plus un mot sur la blockchain*.
* Pas un talk sur l'*informatique quantique*, qui était un des buzz de la précédente édition.
* Etonnament, nous avons été moins "inondés" de talks sur les frameworks Front en JS.

== Conf à voir sur YouTube

* La conf sur "PostGre NoSQL" 
* "D’architecte à Métarchitecte : une évolution nécessaire" de Rémi Cocula (vendredi 14:30)
* "Au secours, mon projet BigData est en production!" par Vincent Devillers (vendredi 16:45)

== Divers

* Voir *Manager* de Saagie pour l'organisation des jobs Big Data (outil à destination des Data Engineer)
	** se renseigner également sur *DataFabric* de Saagie

== Avis sur le salon

* Beaucoup de talks sur *Quarkus*, et les moyens de rendre Java "moins lourd", et aussi pratique d'utilisation (expérience développeur / *"developer joy"*) que des langages comme Node ou Go.
* On continue de beaucoup parler des microservices, surtout de tout l'environnement qui gravite autour (*capability model*), et des meilleurs façons de le mettre en place / gérer au quotidien.
	** On note un petit buzz autour de *MicroProfile*, dont il a été question plusieurs fois 🙂

* On a de nouveau un sac qui déchire en goodies ! 😍
