= Devoxx France 2019 - Buzz words and synthesis
Thomas SCHWENDER <https://github.com/ardemius[@ardemius]>
// Handling GitHub admonition blocks icons
ifndef::env-github[:icons: font]
ifdef::env-github[]
:status:
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]
:imagesdir: ../images
:source-highlighter: highlightjs
// Next 2 ones are to handle line breaks in some particular elements (list, footnotes, etc.)
:lb: pass:[<br> +]
:sb: pass:[<br>]
// check https://github.com/Ardemius/personal-wiki/wiki/AsciiDoctor-tips for tips on table of content in GitHub
:toc: macro
//:toclevels: 3
// To turn off figure caption labels and numbers
:figure-caption!:

toc::[]

.2019/05/07 - Vidéos disponibles sur YouTube
IMPORTANT: Les vidéos des conférences sont maintenant disponibles sur YouTube, via la playlist https://www.youtube.com/playlist?list=PLTbQvx84FrARfJQtnw7AXIw1bARCSjXEI[Devoxx France 2019] de la chaîne Devoxx Fr

== Buzz words & Technos qui ont le vent en poupe

* *Kubernetes / Istio*
* *Quarkus* : comme évolution de Thorntail en tant qu'implémentation de Eclipse MicroProfile, mais est également beaucoup plus que cela, et monte en puissance !
* *GraalVM*, qui implique
	** *SubstrateVM*, qui lui même implique
	** la *compilation Ahead Of Time* (AOT)
* On note toujours plus de poussée du côté de la *programmation réactive*
* *Microservices*
	** Et surtout microservices avec Kubernetes, et *Istio, comme service mesh*, pour gérer les fonctionnalités transverses du Capability Model
	** Plusieurs conf sur *MicroProfile*, comme quoi Java Enterprise continue d'évoluer ! 🙂
* *GraphQL*
* *gRPC* (forcément aidé par Kubernetes)

== Technos dont on parle moins (ou plus !)

* Excepté le talk sur le "shit coin", *plus un mot sur la blockchain*.
* Pas un talk sur l'*informatique quantique*, qui était un des buzz de la précédente édition.
* Etonnament, nous avons été moins "inondés" de talks sur les frameworks Front en JS.

== Conf à voir sur YouTube

* https://www.youtube.com/watch?v=h_l2z-Ti8gg&list=PLTbQvx84FrARfJQtnw7AXIw1bARCSjXEI[PostgreSQL c'est le nouveau NoSQL] de Laurent Doguin
* https://www.youtube.com/watch?v=sEK68arLUq0&list=PLTbQvx84FrARfJQtnw7AXIw1bARCSjXEI[D’architecte à Métarchitecte : une évolution nécessaire] de Rémi Cocula +
-> Vu ! Très bon talk sur le métier d'architecte, tel qu'il devrait être aujourd'hui (et non il y a 20 ans)
* https://www.youtube.com/watch?v=YL7JDO89HWQ&list=PLTbQvx84FrARfJQtnw7AXIw1bARCSjXEI[Au secours, mon projet BigData est en production!] par Vincent Devillers

== Divers

* Voir *Manager* de Saagie pour l'organisation des jobs Big Data (outil à destination des Data Engineer)
	** se renseigner également sur *DataFabric* de Saagie

* L'excellent projet http://todobackend.com/[Todo-Backend], découvert durant l'université sur Quarkus d'Emmanuel et Clément. +
Ce dernier regroupe les (très) nombreuses implémentations d'une même API web, représentant une simple TODO liste, à l'aide d'une vaste combinaison de technologies.

* Les super T-shirts de Takima ont été réalisés par mistertee.fr[Mister Tee]

== Avis sur le salon

* Beaucoup de talks sur *Quarkus*, et les moyens de rendre Java "moins lourd", et aussi pratique d'utilisation (expérience développeur / *"developer joy"*) que des langages comme Node ou Go.
* On continue de beaucoup parler des microservices, surtout de tout l'environnement qui gravite autour (*capability model*), et des meilleurs façons de le mettre en place / gérer au quotidien.
	** On note un petit buzz autour de *MicroProfile*, dont il a été question plusieurs fois 🙂

* On a de nouveau un sac qui déchire en goodies ! 😍
