= Devoxx France 2019 - Microservices: Spring Cloud vs JEE Microprofile?

Spring Microservices vs MicroProfile JEE

== Darren : 

Voilà la liste des link :

* https://spring.io/guides/gs/rest-service/
* https://spring.io/guides/gs/consuming-rest/
* https://spring.io/guides/gs/spring-boot-docker/
* http://eldermoraes.com/2018/07/31/how-to-implement-microservices-using-microprofile-thorntail-and-eclipse-ide/
* https://developers.redhat.com/blog/2018/11/21/eclipse-microprofile-for-spring-boot-developers/
* https://itnext.io/migrating-a-spring-boot-service-to-kubernetes-in-5-steps-7c1702da81b6
* https://www.e4developer.com/2018/01/21/java-enterprise-and-microservices-meet-microprofile/
* https://medium.com/@the.raj.saxena/springboot-2-performance-servlet-stack-vs-webflux-reactive-stack-528ad5e9dadc
* https://itnext.io/migrating-a-spring-boot-service-to-kubernetes-in-5-steps-7c1702da81b6

== Thomas :

Pour la comparaison de 2 stacks microservices complètes, bien penser à :

* comparer l'outillage associé, dont une base va être commune (ex : SonarQube ?)

Fonctionnalités à comparer :

* API Gateway
* Load Balancer
* Service Discovery
* Circuit Breaker

Des exemples d'outils gérant ces 4 fonctionnalités:

* côté Netflix OSS : Zuul / Ribbon / Eureka / Hystrix
* côté Hashicorp : ??? / Fabio / Consul (très à la mode partout en ce moment) / ???

Netflix est peut-être en train d'abandonner une partie de sa stack, ou de la renouveler Voir par exemple Envoy qui pourrait remplacer Zuul : +
https://piotrminkowski.wordpress.com/2017/10/25/envoy-proxy-with-microservices/

Pour la partie sécurité, dans le EJM, en 206/297, on trouve : +
"Standard protocols— Out of the box, Keycloak provides support for OpenID Connect, OAuth 2.0, and Security Assertion Markup Language (SAML)."

Dans notre plan de prez, on pourrait rappeler les différents composants d'une stack microservices (API gateway, Service discovery, Load Balancer, etc.) +
il faudrait se débrouiller pour faire nos exemples Microprofiles et Spring Boot avec les mêmes outils en commun (quand possible biensûr) +
il faudrait essayer de garder une trame commune, pour faciliter la comparaison

== Plan de la présentation

* Refaire un rien d'histoire *très rapide* sur les microservices (définition d'A. Cockburn, applications cloud native, qualité de service et fonctionnalités attendues, etc.)

* Rappel de l'env tech des microservices, et de la qualité de services attendue concernant ces derniers, pour la réalisation d'une application cloud native :

** API Gateway
** Service Discovery
** Load Balancer
** Circuit Breaker
	**** bulkheads
	**** fallbacks
** Centralised configuration (?)
** monitoring and logging
** security

* Description de la stack Spring Boot et Cloud, et des outils avec lesquels elle s'intègre pour rendre la qualité de service :
	** Netflix OSS
		**** Hystrix
		**** Ribbon -> Eureka
	** Spring actuators (logging monitoring)
	** Spring security

== Préparation des slides

IMPORTANT : faire les slides en FRANCAIS ! (Devoxx FR est à 80% francophone)

Rappelez que les applications sont de plus en plus *cloud native* à l'heure actuelle

The common work of a developper is to:

* develop
* secure (check if we add this step or not?)
* test
* package
* deploy
* monitor
* scale their application

As this can be complex, they generally do rely on frameworks to ease those steps. 

When working with Java, *JEE* and *Spring* and 2 common ones

Taken as is, JEE is a specification for an Application Server dedicated to monolithic webapps, whereas Spring Boot and Cloud are designed to build microservices. +
One could say there is nothing to compare, "just choose Spring", but that's just when Microprofile comes into play.

So let's compare Spring Boot and Cloud and Microprofile, and to do so let's quickly remind ourselves what are microservices.

Microservices originated from the Hexagonal Architecture, also known as Ports and Adapters pattern, coined by Alistair Cockburn. +
He describes microservices as:

____
an architectural style or an approach to building IT systems as aset of business capabilities that are autonomous, self-contained, and loosely coupled.
____

This implies that they need to be:

* small:

.https://dzone.com/articles/microservices-in-practice-1
----
The foundation of microservices architecture(MSA) is about developing a single application as a suite of *small* and *independent* services that are running in its own process, developed and deployed independently.
----

* isolated
* reusable

.https://dzone.com/articles/microservices-in-practice-1
----
In the context of SOA, SOA governance guides the development of reusable services, establishing how services will be designed and developed and how those services will change over time.
----

* disposable

The need of *failing fast* 

To guarantee those last, a classic technical stack emerged around the following component:

* API Gateway
* Service Discovery
* Load Balancer
* Circuit Breaker
	** bulkheads
	** fallbacks
* Centralised configuration (?)
* monitoring and logging
* security

== Demo et applications

* Spring

* MicroProfile

On prendrait quelle implémentation pour nos tests ?

* OpenLiberty (IBM) est la plus à jour quant à la version d'Eclipse MicroProfile
* Thorntail (ex Wildfly Swarm, RedHat) est "Thorntail, in its 2.1.0.Final version, is the first MicroProfile container to use the SmallRye implementation." +
Voir https://developers.redhat.com/blog/2018/08/23/eclipse-microprofile-and-red-hat-update-thorntail-and-smallrye/

== Resources

* Microservices "core" :
	** https://fr.slideshare.net/BenWilcock1/microservices-java-ee-vs-spring-boot-and-spring-cloud : old (2016) but GREAT RESOURCE
		**** the associated GitHub repo is also very good (https://github.com/benwilcock/cqrs-microservice-sampler) +
		A detailed explanation of the work done is also available at https://benwilcock.wordpress.com/2016/06/20/microservices-with-spring-boot-axon-cqrses-and-docker/
	** https://dzone.com/articles/microservices-in-practice-1: good def of all elements of the microservices stack
	** Pragmatic Microservices: https://medium.com/microservices-in-practice/microservices-in-practice-7a3e85b6624c TRES BON +
	Une autre bonne présentation des différents éléments de la stack microservices
	** Toutes les explications du site Eclipse.org sur les bases des microservices et fonctions associées (gateway, service discovery) sont très bien faites. Exemple : https://www.eclipse.org/community/eclipse_newsletter/2017/september/article5.php
	** *applications cloud-native* un bon schéma et une def courte et claire "L'approche Cloud-native est la façon dont les applications sont créées et déployées, non pas où elles sont exécutées." : https://www.supinfo.com/articles/single/5015-qu-est-ce-qu-une-application-cloud-native

* Spring Boot and Cloud microservices :
	** Quick Guide to Microservices With Spring Boot 2.0, Eureka, and Spring Cloud : https://dzone.com/articles/quick-guide-to-microservices-with-spring-boot-20-e

* Eclipse MicroProfile :
	** cette suite d'articles d'Eclipse.org, traitent également de l'env tech autour des microservices : https://www.eclipse.org/community/eclipse_newsletter/2017/september/
	** Red Hat's implementation of Eclipse MicroProfile, WildFly Swarm, has been renamed to *Thorntail*.
	** Eclipse MicroProfile Releases and associated implementation: https://wiki.eclipse.org/MicroProfile/Implementation
	** Here comes *SmallRye*, a shared Eclipse MicroProfile implementation: https://developers.redhat.com/blog/2018/08/23/eclipse-microprofile-and-red-hat-update-thorntail-and-smallrye/
	** dev "core" de microservices avec MicroProfile (sans l'env tech adjacent) : https://www.baeldung.com/eclipse-microprofile

	** env tech avec MicroProfile, voir *KumuluzEE* (Java Duke’s Choice Award Winner) which provides support for service discovery by introducing simple annotations for REST services: https://ee.kumuluz.com/microprofile +
	-> problème : KumuluzEE is fully compliant with Eclipse MicroProfile 1.0, 1.1 and 1.2. -> donc pas les versions les plus récentes
	** Toujours sur KumuluzEE, que l'on pourrait voir comme un concurrent de Spring Cloud : https://piotrminkowski.wordpress.com/tag/microprofile/
	+
	----
	*What’s KumuluzEE*
	Can KumuluzEE be a competitor for the Spring Cloud framework? He is certainly not as popular and advanced in the solutions for microservices like Spring Cloud, but has basic modules for service registration, discovery, distributed configuration propagation, circuit breaking, metrics and support for Docker and Kubernetes. It uses CDI on JBoss Weld container for dependency injection and Jersey as a REST API provider. Modules for configuration and discovery basing on Consul or etcd and they are rather on early stage of development (1.0.0-SNAPSHOT), but let’s try it out.
	----
	** RAHHHH, Istio Istio Istio qui semble être une solution de plus en plus préco pour MP : https://www.eclipse.org/community/eclipse_newsletter/2018/september/MicroProfile_istio.php (en plus un article récent !) -> *A LIRE ABSOLUMENT !!!!*

* Comparaison entre Spring Boot / Cloud et MicroProfile :
	** https://www.ibm.com/blogs/bluemix/2018/09/migrate-java-microservices-from-spring-to-microprofile-p1/ : en fait, bien chercher dans les "how-tos" d'IBM qui a migré de Spring à MicroProfile sa stack Microservices. +
	Le seul "hic" est qu'il faut chercher dans les différents how-to les articles associés à cette migration. Mais, ceci mis à part, c'est une très bonne ressource.
	** Pour la partie vraiment "core" du dev des microservices : https://developers.redhat.com/blog/2018/11/21/eclipse-microprofile-for-spring-boot-developers/ +
	-> *Attention*, cela ne couvre PAS l'environnement technique adjacent (API gateway, service discovery, etc.)

=== Reminders

.https://thenewstack.io/from-monolith-to-microservices/
----
Alistair Cockburn introduced the “ports and adapters” pattern, also called hexagonal architecture, in the context of building applications that can be tested in isolation. However, it has been increasingly used for building reusable microservices-based systems, as advocated by James Gardner and Vlad Mettler. A hexagonal architecture is an implementation of a pattern called  bounded context, wherein the capabilities related to a specific business domain are insulated from any outside changes or effects.
----

.What are microservices? - https://hub.packtpub.com/capability-model-microservices/
----
Microservices originated from the idea of Hexagonal Architecture coined by Alister Cockburn. Hexagonal Architecture is also known as thePorts and Adapters pattern.
----

.Microservices definition from Alistair Cockburn
----
Microservices originated from the idea of Hexagonal Architecture coined by Alister Cockburn. Hexagonal Architecture is also known as the Ports and Adapters pattern.

Microservices is an architectural style or an approach to building IT systems as aset of business capabilities that are autonomous, self-contained, and loosely coupled.
----

For this last ref, check:

* https://hub.packtpub.com/microservices-and-service-oriented-architecture/
* https://hub.packtpub.com/capability-model-microservices/

Good characteristics for microservices: https://stackoverflow.com/questions/48653762/how-microservices-are-different-from-isolated-standalone-service

Especially do not forget the argument on *independent life cycles* to use Conway's law to your advantage.

* https://blog.bernd-ruecker.com/3-common-pitfalls-in-microservice-integration-and-how-to-avoid-them-3f27a442cd07: excellent ref

----
Microservices are about decomposition, but giving each component a high degree of autonomy and isolation
----

This link also explains the importance of *failing fast*

* Parlez de CQRS / ES, et donc prévoir quelques mots sur *Axon framework*. 

* Il faudra peut-être (en fait, *SUREMENT*) également commencer par dire 2 mots sur la comparaison entre plateforme, comme *Istio*, et frameworks, comme *Spring* et *MicroProfile*, pour l'env tech des microservices. +
A ce sujet, voir la prez à Devoxx UK 2018 de Kate Stanley & Adam Pilkington (IBM) : https://www.youtube.com/watch?v=lFj8X0VLOFQ

Pour rappel : "Istio is an Open *platform* to connect, manage and secure microservices" +
Il prend en charge les fonctionnalités suivantes :

* Service Mesh
* Intelligent Routing and Load Balancing
* Fault Tolerance
* Policy Enforcement
* Metrics, Logging, Observability, Visualisation
* Service Identity and Security

Concernant Istio, le side car *Envoy* réalise les fonctionnalités suivantes :

* High performance C++ Proxy
* Load balancing
* Circuit breaking
* Health checks
* Fault injection

==== Kubernetes as a replacement for service registry, discovery and load balancing instead of Netflix OSS

Cette tendance se confirme de plus en plus, bien aidée par l'avènement de l'industrialisation des containers.

check https://www.ibm.com/blogs/bluemix/2017/05/key-decisions-when-building-microservices-apps-in-java-with-kubernetes/ :

----
Q3: How do I handle application service registry and discovery?

To benefit from the many Microservices you create in a distributed, elastic cloud environment, a proper service registration and discovery strategy is critical to allow them to communicate with each other or to be consumed. As a pioneer in cloud-native Microservices implementation, Netflix has built and released a set of opinionated libraries known as Netflix OSS, such as Eureka, Zuul, Ribbon, etc. And they are well integrated with the Spring framework. Typically, services are registered to Eureka, and Ribbon/Zuul handle the service discovery and basic load-balancing. However, what I describe was nearly 5 years ago.

Today, Kubernetes natively supports service registry, discovery and load balancing. You no longer need Netflix OSS for these tasks. Instead, you design the system the Kubernetes way. You can leverage Kubernetes’ Service type to expose your Microservices, then it automatically registered into Kubernetes system via virtual IP or DNS approach (I’ll elaborate on this decision in the next question/answer). The discovery will be through the familiar DNS lookup style. For Service-based clusters, Kubernetes provides a built-in load balancer to distribute the workload among Pods (containers).
----

== Teaser et abstract

*Titre* :

* Microservices war! Spring vs Microprofile!
* Microservices battlefield! Spring vs Microprofile!
* *Microservices: Infinity War! Spring vs MicroProfile*

*Thèmes* : Cloud, Containers et Infrastructure, DevOps

*Niveau* : ouvert à tout niveau d'audience, débutant comme expert

*Type de présentation* : Slides et du code

*Abstract* :

idées à développer dans l'abstract : 

* environnement technique complexe
* donc on utilise des frameworks pour se simplifier la vie
* Spring, Boot et Cloud, est omniprésent, mais MicroProfile est maintenant un challenger
* peut-il espérer concurrencer Spring ?

----
En ce début 2019, et avec maintenant quelques années de recul (et quelques crises de nerf ?) sur le sujet, tout le monde s'accorde à dire que l'environnement technique nécessaire à la mise en place de **microservices** est complexe :
API gateway, service discovery et registry, design for failures et circuit breaker, gestion de la sécurité via OAuth et OpenID Connect, et j'en passe...

Le framework **Spring**, plus particulièrement les projets **Boot** et **Cloud**, a permis à bien des développeurs de préserver (une partie de ? 😉 ) leurs cheveux en facilitant cette mise en place.
Mais est-il seul roi en son domaine, ou existe-t-il des alternatives ?
Créé fin 2016 sur base de Java EE 7, le projet **Eclipse MicroProfile** a justement pour objectif d'optimiser la plateforme Java EE pour les architectures microservices.
Pourra-t-il concurrencer l'hégémonie du premier ?

Durant cette université, **nous comparerons les forces et faiblesses** de ces 2 plateformes via le **développement simultané, pour chacune d'elles, d'une même application**.  
Vous pourrez ainsi, en toute connaissance de cause, choisir de rester sur votre Spring, ou au contraire basculer sur le nouveau MicroProfile 😉
----

Message pour le comité :

----
Bonjour,

Le but de cette université est de **comparer les possibilités des frameworks Spring et MicroProfile pour le développement de microservices**, et leurs facilités d'intégration avec les outils du marché (Netflix OSS, stack Hashicorp avec Consul & Co, mais aussi l'omniprésent Istio du moment, etc.) assurant la qualité de service requise par les applications cloud-native (service discovery, load balancing, gestion des erreur, configuration centralisée, etc.).

On ne va pas se mentir, actuellement, pour le déploiement de microservices, Spring est de loin la stack la plus connue et utilisée.  
Or justement, nous voudrions justement montrer qu'elle n'est pas la seule, et que l'on peut **faire de belles choses avec notre "bon vieux" Java Enterprise**, ici avec MicroProfile 😉

Au final, nous voulons qu'en sortant de l'université, les participants sachent qu'elles sont les forces et faiblesses de chaque stack, et s'ils doivent en choisir eux-mêmes une à l'avenir, ne se contente plus d'un "Spring par défaut".

Côté speakers, Darren et moi faisons partie du **JUG Interne de Softeam depuis des années**.  
Pour une petite idée de notre activité, voir [les CR de nos réunions mensuelles sur GitHub](https://github.com/softeamfr/startech-meetings-reports).  
Nous sommes tous deux des devs seniors avec plus de 12 et 15 ans d'expérience, et plusieurs années d'architecture derrière nous.  
Via notre activité au JUG (voir [cette présentation](https://ardemius.github.io/slides-startech/slides-starTECH.html) pour plus de détails sur celle-ci) nous avons déjà donné de nombreuses formations aux développeurs de la société, sur des sujets variés (*Java core*, *Lambdas*, *optimisation*, *Spring*, *Git*, *TDD*, *AsciiDoctor*, etc.), nous avons donc l'habitude de prendre la parole en public.

Darren a été **enseignante en université pendant 6 ans** sur UML, ainsi qu'en développement web en Java / Java EE.  
De mon côté, **j'ai déjà été speaker à Devoxx France en 2017**, avec le sujet ["Sorcellerie en Java : outrepasser les interdits avec sun.misc.Unsafe"](https://cfp.devoxx.fr/2017/talk/FEU-0240/Sorcellerie_en_Java_:_outrepasser_les_interdits_avec_sun.misc.Unsafe.html) ([YouTube](https://youtu.be/FytJ4OdGYPM)), avec lequel j'avais également gagné le Young Blood du Paris JUG la même année ([YouTube](https://youtu.be/mPvhzKLb9K0))  
Je fais également parti du pôle formation de Softeam, tout particulièrement concernant Git.  
Une bonne partie de mon activité et ma veille est visible sur mes repo GitHub : [https://github.com/Ardemius](https://github.com/Ardemius)
----

Mots clés : microservices, Spring, MicroProfile, (Java EE)





