= Devoxx France 2021 - Buzz words and synthesis
Thomas SCHWENDER <https://github.com/ardemius[@ardemius]>
// Handling GitHub admonition blocks icons
ifndef::env-github[:icons: font]
ifdef::env-github[]
:status:
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]
:imagesdir: ./images
:source-highlighter: highlightjs
// Next 2 ones are to handle line breaks in some particular elements (list, footnotes, etc.)
:lb: pass:[<br> +]
:sb: pass:[<br>]
// check https://github.com/Ardemius/personal-wiki/wiki/AsciiDoctor-tips for tips on table of content in GitHub
:toc: macro
:toclevels: 4
// To number the sections of the table of contents
:sectnums:
// To turn off figure caption labels and numbers
:figure-caption!:
// Same for examples
//:example-caption!:
// To turn off ALL captions
// :caption:

toc::[]

.2021/xx/yy - Vidéos disponibles sur YouTube
IMPORTANT: Les vidéos des conférences seront bientôt disponibles sur sur https://www.youtube.com/channel/UCsVPQfo5RZErDL41LoWvk0A[chaîne YouTube de Devoxx France].

== Buzz words & Technos qui ont le vent en poupe

* *Kubernetes* : même s'il fait toujours peur aux clients, on se rapproche encore un peu plus de "l'âge de la maturité"
	** Istio dans la foulée, comme le compagnon, maintenant obligatoire, de Kubernetes
* Importance critique des *Availability Zones* dans le Cloud
* *DataDog* et *Grafana* pour le monitoring
* *Ansible* pour la configuration
* *PostGre* comme BDD en force
* *Redis* pour du cache
* *Quarkus* dont l'adoption s'amplifie

== Technos dont on parle moins (ou plus !)

* rien n'a été "conspué" cette année à ma connaissance...

== Conf à voir sur YouTube

* "J'aime le Big-O mais il me trompe"

== Avis sur le salon

Evidemment, du fait du COVID et des mesures sanitaires, ce Devoxx était bien différent des autres : pas de goodies, pas de Meet & Greet, pas de dîner des speakers, moins de conférences et moins d'exposants d'où son nom : édition "9 3/4" +
MAIS, ce Devoxx a eu le mérite d'exister, et nous a quand même permis de passer un bon moment, avec quelques très bons talks.

Ma conférence préférée du salon : "La cohésion de groupe en analyse transactionelle : une clef du leadership mise en perspective pratique par l'architecture" d'Anne-Sophie et Alexis LE MAULT. +
Un talk de référence sur le leadership et la cohésion d'équipe à mettre entre les mains de tous les managers et leaders.

Le projet https://makair.life/[MakAir], présenté dans une Keynote de Quentin ADAM et dans un stand, était également renversant. +
Ce projet est l'illustration de la vélocité de nos méthodes de conception dans "l'informatique", où en 3 4 mois, un groupe a pu développer et produire un produit qui aurait mis 3 ou 4 ans et 8x le coût à sortir dans une boîte médicale "classique".

