= Jeudi 16:10 / 16:55 - Effective Java, Third Edition: Keepin' it Effective
Thomas SCHWENDER <https://github.com/ardemius[@ardemius]>
// Handling GitHub admonition blocks icons
ifndef::env-github[:icons: font]
ifdef::env-github[]
:status:
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]
:imagesdir: ../images
:source-highlighter: highlightjs
// Next 2 ones are to handle line breaks in some particular elements (list, footnotes, etc.)
:lb: pass:[<br> +]
:sb: pass:[<br>]
// check https://github.com/Ardemius/personal-wiki/wiki/AsciiDoctor-tips for tips on table of content in GitHub
:toc: macro
//:toclevels: 3
// To turn off figure caption labels and numbers
:figure-caption!:

toc::[]

Par Joshua Bloch, author of Effective Java (among numerous other things...). +
https://cfp.devoxx.fr/2018/talk/TXO-1273/Effective_Java%2C_Third_Edition%3A_Keepin%27_it_Effective[Descriptif de la conférence sur le site du CFP de Devoxx] +
icon:tags[] Key words : Java, Lambda, Java Streams API

// ifdef::env-github[]
// https://www.youtube.com/watch?v=XXXXXX[vidéo de la présentation sur YouTube]
// endif::[]
// ifdef::env-browser[]
// video::XXXXXX[youtube, width=640, height=480]
// endif::[]

== Overview

====
Since its release in 2001, Effective Java has been the de facto standard best-practices guide for the Java platform. +
The book was last updated in 2008, when Java 6 was released. +
In the intervening decade, the platform has had three major releases, introducing many new language and library features that significantly affect best practices. 

The recently released third edition of Effective Java contains one new chapter, fourteen new items, and numerous changes to existing items. 

This talk covers some highlights from the third edition, concentrating on streams and lambdas.
====

== Notes

.The evolution of Effective Java
image::1

=== prefer lambdas to anonymous classes

You must understand *generics* to use *Lambdas*.

=== prefer method references to lambdas

.Les 5 types
image::2

=== Favor standard functional interfaces

=== Use streams judiciously

image::3

image::4

== Avis

Le livre est déjà dans ma bibliothèque.
