= Xebicon 2019
Thomas SCHWENDER <https://github.com/ardemius[@ardemius]>
// Handling GitHub admonition blocks icons
ifndef::env-github[:icons: font]
ifdef::env-github[]
:status:
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]
:imagesdir: ./images
:source-highlighter: highlightjs
// Next 2 ones are to handle line breaks in some particular elements (list, footnotes, etc.)
:lb: pass:[<br> +]
:sb: pass:[<br>]
// check https://github.com/Ardemius/personal-wiki/wiki/AsciiDoctor-tips for tips on table of content in GitHub
:toc: macro
:toclevels: 1
// To turn off figure caption labels and numbers
//:figure-caption!:
// Same for examples
//:example-caption!:
// To turn off ALL captions
:caption:

toc::[]

Le 28/11/2019, au palais Brogniart à Paris.

== Présentation

* *Site* : https://xebicon.fr/
* *Schedule* : https://xebicon.fr/programme-xebicon-2019/

== Keynote d'ouverture - XebiKart

== On-demand development environments with Kubernetes (talk in english)

https://xebicon.fr/programme-xebicon-2019/#event-87[]

====
Retour d'Expérience Client (REX)

When releasing to production 5 times a day or more, any feature should be strongly tested and validated with a dedicated environment that is similar to production.

At JobTeaser, any Pull Request can lead to the bootstrap of such an environment on-the-fly. We call them Feature-envs.

Depending on what you need to test, the production "similarities" can differ. Do you need the same scale as production? Should the URL be customized? How do your manage clean-up?

Today, we will deliver all our secrets to manage those environments at scale with a Kubernetes cluster.

Enrico La Cava, Infrastructure Unreliability Engineer - JobTeaser
Olivier Cloirec, Consultant SRE
====

==


== Buzz words



== Divers























