= Devoxx France 2018 - Buzz words and synthesis
:lb: pass:[<br> +]
:imagesdir: ../images
:icons: font
:source-highlighter: highlightjs

.2018/05/03 - Vidéos disponibles sur YouTube
IMPORTANT: Les vidéos des conférences sont maintenant disponibles sur YouTube, via la playlist https://www.youtube.com/playlist?list=PLTbQvx84FrARa9pUtZYK7t_UfyGMCPOBn[Devoxx France 2018] de la chaîne Devoxx Fr

== Buzz words

* *DevOps* en général, et tout particulièrement :
	** *Kubernetes* qui a pris le pouvoir parmi les orchestrateurs de containers
	** *Chaos engineering* dont on attend parler de plus en plus

* La mémoire *Off Heap* en Java est toujours un sujet d'actualité, malgré la fin annoncé de la classe `Unsafe`.

* *Spark* : l'avènement, il est partout, mais 

* *Kafka* qu'on essaye maintenant de mettre partout, même quand ce n'est pas forcément une bonne idée... +
A noter que l'écosystème Kafka (Connect, Streams, etc.) est très fortement poussé par Confluent, afin d'étendre ses use cases au-delà du simple MoM.
	** Kafka pousse également le concept de *Data Stream* (comme une évolution des DWH et Datalake)

* *Microservices* encore et encore, avec le constat que c'est compliqué, et qu'il faut prendre le temps de les maîtriser et s'équiper en conséquence

* *DDD*, *CQRS* et *Event sourcing* : nous allons de plus en plus y être (massivement) confrontés, il faut donc connaître ces méthodes de conception.
* C'était déjà le cas ces dernières années avec l'avènement de NodeJS, mais il faut maintenant encore plus connaître *l'Event Loop*
* *Hexagonal architecture*
* Programmation *Reactive*

* *flatMap*
* programmation fonctionnelle (surtout les fonctionnalités disponibles via Java 8)

* *Informatique quantique* : on commence à en parler (et dire que cela faisait partie des talks que je n'ai pas eu le temps de présenter... Rah !)
* Beaucoup de DevOps

NOTE: L'expression *"Big Data"* est définitivement en fin de vie, et en train d'être simplement *remplacée par le simple concept de "Data"*. +
Ce dernier intègre progressivement les projets "les plus classiques" et le langage commun, et est sur le chemin de devenir une brique de base de la conception d'application (-> d'ici quelques temps, on ne dira plus que l'on fait du "big data" sur un projet)

.En conclusion
[IMPORTANT]
====
On continue à noter une *explosion du nombre de technologies, outils et méthodologies* disponibles sur le marché (bien aidée par la généralisation du traitement de la Data et https://hadoopecosystemtable.github.io/[l'écosystème Hadoop])

Personne ne peut toutes les connaître, nous allons donc être de plus en plus confrontés à des façons différentes d'obtenir un même résultat. +
-> Plus que nos connaissances spécifiques des technologies, c'est *notre capacité d'adaptation* à celle que nous ne connaissons pas qui va devenir (encore plus) capitale.
====

== Technos qui ont le vent en poupe

* *Kubernetes*
* *Kafka*
* *Spark*
* Hashicorp Vault
* gRPC

//-

* https://kahoot.it[*Kahoot.it*] pour les questionnaires, jeux de question / réponses en ligne. +
Pour information, nous l'utilisons déjà pour nos Town Halls et autres meetings à la SGCIB.
* *Asciidoctor* est de plus en plus utilisé pour les notes et les slides (avec l'addition d'un backend approprié)

=== Technos / outils à tester absolument

* Sparkube
* Istio
* gRPC

== Conf à voir sur YouTube

* https://cfp.devoxx.fr/2018/talk/UHI-5975/Guide_de_survie_NodeJS_pour_le_developpeur_Java[Guide de survie NodeJS pour le développeur Java]

* Université d'organisation perso et pro (GTD, Personal Kanban, Inbox 0) : https://cfp.devoxx.fr/2018/talk/INR-2511/Lab_productivite_personnelle%3A_l%E2%80%99optimisation_de_soi[Lab productivité personnelle: l’optimisation de soi]

* https://cfp.devoxx.fr/2018/talk/UTJ-8549/Etre_architecte_logiciel_en_2018[Être architecte logiciel en 2018]

* Les 3 conférences sur les enfants et le code :
	** https://cfp.devoxx.fr/2018/talk/WCA-4379/Ce_que_les_enfants_m'ont_appris_lorsque_j'ai_essaye_de_leur_apprendre_a_coder.[Ce que les enfants m'ont appris lorsque j'ai essayé de leur apprendre à coder.]
	** https://cfp.devoxx.fr/2018/talk/FTO-9618/Le_jaillissement_de_l'esprit[Le jaillissement de l'esprit]
	** https://cfp.devoxx.fr/2018/talk/QNS-5990/un_Loof_ca_va,_de_Loof_bonjour_les_degats_%F0%9F%98%9C[un Loof ça va, de Loof bonjour les dégâts 😜]

* Conférence sur l'informatique quantique (et dire que c'était mon sujet en préparation... Donnez-moi plus de tempppssssss !) : https://cfp.devoxx.fr/2018/talk/FSM-3825/Quand_Internet_sera_gouvernee_par_les_%7C%F0%9F%99%80%3E_de_Shrodinger[Quand Internet sera gouvernée par les |🙀> de Shrödinger]

== Divers

* Info sympa de Philippe (LAWSON, ancien collège chez Kompass) : bon cursus de Data Architect disponible sur OpenClassrooms

* Slides du talk de jeudi sur Karate générés automatiquement en Asciidoctor 🙂 +
Voir https://github.com/binout/karate-devoxxfr2018 pour les détails

== Synthèse

Toujours aussi sympa et intéressant, dès lors que l'on choisit les bonnes conférences :wink:

Juste quelques (tous) petits bémols par rapport à la version 2017 :

* il fallait prendre séparément sandwich, entrée et dessert contrairement à la version 2017 où l'on pouvait prendre un sac repas contenant déjà tout. +
Je me dis que le recyclage dess-dits sacs (tissu) devait être problématique, d'où leur absence cette année.

* le sac Devoxx 2018 n'est absolument pas à la hauteur du 2018, et je l'attendais comme le messie 😭
